[package]
name = "gitflow-exercise"
version = "0.1.0-alpha.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.61", features = ["backtrace"] }
tokio = { version = "1.20.1", features = ["full"] }
