name: Rust - PR Actions

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      run: cargo clippy --all -- -D warnings
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Unit Tests
      run: cargo test --verbose
